# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Music Player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Music Player
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FirebaseMessaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Crash'

  target 'Music PlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
